# Generated by Django 5.2.7 on 2025-11-06 12:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0012_busservice_bus_number_busservice_bus_travels_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderPerformance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_bookings', models.PositiveIntegerField(default=0)),
                ('avg_occupancy', models.FloatField(default=0.0)),
                ('active_services', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_performance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RouteAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_bookings', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('avg_occupancy', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('active_providers', models.PositiveIntegerField(default=0)),
                ('active_services', models.PositiveIntegerField(default=0)),
                ('bus_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('train_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('flight_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('misc_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_destination', to='services.station')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_source', to='services.station')),
            ],
            options={
                'verbose_name_plural': 'Route Analytics',
                'unique_together': {('source', 'destination')},
            },
        ),
    ]
