# Generated by Django 5.2.7 on 2025-10-19 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='provider_user',
            new_name='provider_user_id',
        ),
    ]
