# Generated by Django 5.2.7 on 2025-10-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='device',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
