# Generated by Django 5.2.7 on 2025-10-15 10:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('policy_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cancellation_window', models.PositiveIntegerField(help_text='Hours before departure')),
                ('cancellation_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reschedule_allowed', models.BooleanField(default=True)),
                ('reschedule_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('no_show_penalty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('terms_conditions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('distance_km', models.FloatField()),
                ('estimated_duration', models.DurationField()),
                ('via_points', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registration_no', models.CharField(max_length=50, unique=True)),
                ('model', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField()),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Maintenance', 'Maintenance')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BusService',
            fields=[
                ('service_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Active', 'Active'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20)),
                ('num_rows_sleeper', models.PositiveIntegerField(default=0)),
                ('num_columns_sleeper', models.PositiveIntegerField(default=0)),
                ('num_rows_non_sleeper', models.PositiveIntegerField(default=0)),
                ('num_columns_non_sleeper', models.PositiveIntegerField(default=0)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sleeper_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('non_sleeper_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dynamic_pricing_enabled', models.BooleanField(default=False)),
                ('dynamic_factor', models.FloatField(default=1.0)),
                ('current_sleeper_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('current_non_sleeper_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_capacity', models.PositiveIntegerField(default=0)),
                ('booked_seats', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_services', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.policy')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.route')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='BusSeat',
            fields=[
                ('seat_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seat_number', models.CharField(max_length=10)),
                ('seat_type', models.CharField(choices=[('Sleeper', 'Sleeper'), ('NonSleeper', 'NonSleeper')], max_length=20)),
                ('is_booked', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bus_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='services.busservice')),
            ],
        ),
        migrations.CreateModel(
            name='FlightService',
            fields=[
                ('service_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('flight_number', models.CharField(max_length=20)),
                ('airline_name', models.CharField(max_length=100)),
                ('aircraft_model', models.CharField(default='Boeing 737', max_length=100)),
                ('num_rows_business', models.PositiveIntegerField(default=0)),
                ('num_columns_business', models.PositiveIntegerField(default=0)),
                ('num_rows_premium', models.PositiveIntegerField(default=0)),
                ('num_columns_premium', models.PositiveIntegerField(default=0)),
                ('num_rows_economy', models.PositiveIntegerField(default=0)),
                ('num_columns_economy', models.PositiveIntegerField(default=0)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('business_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('premium_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('economy_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dynamic_pricing_enabled', models.BooleanField(default=False)),
                ('dynamic_factor', models.FloatField(default=1.0)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Active', 'Active'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20)),
                ('total_capacity', models.PositiveIntegerField(default=0)),
                ('booked_seats', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_services', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.policy')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.route')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='FlightSeat',
            fields=[
                ('seat_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seat_number', models.CharField(max_length=10)),
                ('seat_class', models.CharField(choices=[('Business', 'Business'), ('PremiumEconomy', 'Premium Economy'), ('Economy', 'Economy')], max_length=20)),
                ('is_booked', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('flight_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_seats', to='services.flightservice')),
            ],
        ),
        migrations.CreateModel(
            name='TrainService',
            fields=[
                ('service_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('train_name', models.CharField(max_length=100)),
                ('train_number', models.CharField(max_length=20, unique=True)),
                ('num_bogies', models.PositiveIntegerField()),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sleeper_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('second_ac_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('third_ac_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dynamic_pricing_enabled', models.BooleanField(default=False)),
                ('dynamic_factor', models.FloatField(default=1.0)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Active', 'Active'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20)),
                ('total_capacity', models.PositiveIntegerField(default=0)),
                ('booked_seats', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.policy')),
                ('provider_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_services', to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.route')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='TrainSeat',
            fields=[
                ('seat_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bogie_number', models.PositiveIntegerField()),
                ('seat_number', models.CharField(max_length=10)),
                ('seat_type', models.CharField(choices=[('Lower', 'Lower'), ('Middle', 'Middle'), ('Upper', 'Upper'), ('SideLower', 'Side Lower'), ('SideUpper', 'Side Upper')], max_length=20)),
                ('class_type', models.CharField(choices=[('Sleeper', 'Sleeper'), ('SecondAC', 'Second AC'), ('ThirdAC', 'Third AC')], max_length=20)),
                ('is_booked', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('train_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_seats', to='services.trainservice')),
            ],
        ),
    ]
