# Generated by Django 5.2.7 on 2025-10-15 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='registration_no',
            field=models.CharField(max_length=50),
        ),
    ]
