# Generated by Django 5.2.7 on 2025-10-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_vehicle_registration_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainservice',
            name='train_number',
            field=models.CharField(max_length=20),
        ),
    ]
