# Generated by Django 5.2.7 on 2025-10-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_trainservice_train_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='destination_dropoff_points',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='intermediate_stops',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='route',
            name='source_pickup_points',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
