# Generated by Django 5.2.7 on 2025-10-19 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_route_destination_dropoff_points_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='via_points',
        ),
    ]
