# Generated by Django 5.2.7 on 2025-10-21 13:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_remove_route_via_points'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainseat',
            name='is_booked',
        ),
        migrations.RemoveField(
            model_name='trainseat',
            name='price',
        ),
        migrations.AddField(
            model_name='policy',
            name='no_cancellation_fee_markup',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='no_reschedule_fee_markup',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='trainseat',
            name='availability_mask',
            field=models.CharField(blank=True, help_text="A string of '0's (free) and '1's (booked) for each segment.", max_length=100),
        ),
        migrations.RemoveField(
            model_name='route',
            name='intermediate_stops',
        ),
        migrations.AlterField(
            model_name='trainservice',
            name='base_price',
            field=models.DecimalField(decimal_places=2, help_text='Full route base price (e.g., Sleeper)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='trainservice',
            name='second_ac_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Full route price for Second AC', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='trainservice',
            name='sleeper_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Full route price for Sleeper', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='trainservice',
            name='third_ac_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Full route price for Third AC', max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(blank=True, help_text='Optional short code', max_length=20, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('saved_by', models.ManyToManyField(blank=True, help_text='Users who have saved this station as a favorite.', related_name='saved_stations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_order', models.PositiveIntegerField()),
                ('price_to_destination', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('duration_to_destination', models.DurationField(blank=True, null=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='services.route')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.station')),
            ],
            options={
                'ordering': ['stop_order'],
                'unique_together': {('route', 'stop_order')},
            },
        ),
        migrations.AlterField(
            model_name='route',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes_to', to='services.station'),
        ),
        migrations.AlterField(
            model_name='route',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes_from', to='services.station'),
        ),
        migrations.CreateModel(
            name='TrainServiceSegment',
            fields=[
                ('segment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('segment_index', models.PositiveIntegerField()),
                ('available_count_sleeper', models.PositiveIntegerField(default=0)),
                ('available_count_second_ac', models.PositiveIntegerField(default=0)),
                ('available_count_third_ac', models.PositiveIntegerField(default=0)),
                ('from_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departing_segments', to='services.station')),
                ('to_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arriving_segments', to='services.station')),
                ('train_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='services.trainservice')),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='intermediate_stops',
            field=models.ManyToManyField(blank=True, related_name='stops_on_routes', through='services.RouteStop', to='services.station'),
        ),
    ]
