# Generated by Django 5.2.7 on 2025-10-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_remove_trainseat_is_booked_remove_trainseat_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainservice',
            name='booked_seats',
        ),
        migrations.RemoveField(
            model_name='trainservice',
            name='num_bogies',
        ),
        migrations.AddField(
            model_name='trainservice',
            name='bogies_config',
            field=models.JSONField(default=dict, help_text="JSON object describing bogie configuration. e.g., {'Sleeper': {'count': 10, 'seats_per_bogie': 72}}"),
        ),
    ]
