# Generated by Django 5.2.7 on 2025-10-21 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_remove_trainservice_booked_seats_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainservicesegment',
            options={'ordering': ['segment_index']},
        ),
        migrations.AlterUniqueTogether(
            name='trainservicesegment',
            unique_together={('train_service', 'segment_index')},
        ),
    ]
