# Generated by Django 5.2.7 on 2025-10-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_trainservicesegment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='BusStations',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='state',
            field=models.CharField(blank=True, default='India', max_length=100, null=True),
        ),
    ]
