# Generated by Django 5.2.7 on 2025-10-24 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_provider'),
        ('services', '0009_station_busstations_station_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='busseat',
            name='booking_passenger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bus_seat_bookings', to='bookings.bookingpassenger'),
        ),
        migrations.AddField(
            model_name='flightseat',
            name='booking_passenger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flight_seat_bookings', to='bookings.bookingpassenger'),
        ),
    ]
