# Generated by Django 5.2.7 on 2025-10-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_busseat_booking_passenger_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='estimated_duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
