# Generated by Django 5.2.7 on 2025-10-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_alter_route_estimated_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='busservice',
            name='bus_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='busservice',
            name='bus_travels_name',
            field=models.CharField(blank=True, default='Placeholder', max_length=100, null=True),
        ),
    ]
