# Generated by Django 5.2.7 on 2025-10-22 18:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0004_booking_provider'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255)),
                ('message_body', models.TextField()),
                ('channel', models.CharField(choices=[('Email', 'Email')], default='Email', max_length=10)),
                ('target_audience_type', models.CharField(choices=[('Service', 'All users of a specific service'), ('Provider', 'All users of the provider'), ('Passenger', 'A specific passenger'), ('Booking', 'A specific booking'), ('Custom', 'A custom list of users')], default='Custom', help_text='Defines the group this notification is intended for.', max_length=20)),
                ('object_id', models.UUIDField(blank=True, help_text="For 'Service' audience: the UUID of the service instance.", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, help_text="For 'Booking' audience: the specific booking.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='bookings.booking')),
                ('booking_passenger', models.ForeignKey(blank=True, help_text="For 'Passenger' audience: the specific passenger.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='bookings.bookingpassenger')),
                ('content_type', models.ForeignKey(blank=True, help_text="For 'Service' audience: the model of the service (e.g., BusService).", null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationReceipt',
            fields=[
                ('receipt_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Sent', 'Sent'), ('Failed', 'Failed'), ('Read', 'Read')], default='Pending', max_length=10)),
                ('sent_to_address', models.EmailField(blank=True, help_text='The email address this was sent to.', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, help_text='Timestamp when the email was successfully sent.', null=True)),
                ('read_at', models.DateTimeField(blank=True, help_text='Timestamp when the notification was read.', null=True)),
                ('error_message', models.TextField(blank=True, help_text="Error message if status is 'Failed'.", null=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='Notifications.notification')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('notification', 'recipient')},
            },
        ),
    ]
