# Generated by Django 5.2.7 on 2025-11-10 11:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255)),
                ('message_body', models.TextField()),
                ('channel', models.CharField(choices=[('Email', 'Email')], default='Email', max_length=10)),
                ('target_audience', models.CharField(choices=[('ALL_USERS', 'All Users'), ('ALL_PROVIDERS', 'All Providers'), ('ALL_ADMINS', 'All Admins'), ('SERVICE_CUSTOMERS', 'Service Customers'), ('PROVIDER_CUSTOMERS', 'Provider Customers'), ('SPECIFIC_PROVIDER', 'Specific Provider'), ('SPECIFIC_CUSTOMER', 'Specific Customer')], max_length=50)),
                ('provider_id', models.UUIDField(blank=True, help_text='Used if target_audience is SPECIFIC_PROVIDER or PROVIDER_CUSTOMERS', null=True)),
                ('customer_id', models.UUIDField(blank=True, help_text='Used if target_audience is SPECIFIC_CUSTOMER', null=True)),
                ('service_id', models.UUIDField(blank=True, help_text='Used if target_audience is SERVICE_CUSTOMERS', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('sender', models.ForeignKey(blank=True, help_text='Admin who created/sent this notification.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_notifications_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Notification',
                'verbose_name_plural': 'Admin Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminNotificationReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sent_to_address', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Sent', 'Sent'), ('Failed', 'Failed'), ('Read', 'Read')], default='Pending', max_length=10)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='Notifications.adminnotification')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_notification_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Notification Receipt',
                'verbose_name_plural': 'Admin Notification Receipts',
                'ordering': ['-created_at'],
                'unique_together': {('notification', 'recipient')},
            },
        ),
    ]
