# Generated by Django 5.2.7 on 2025-10-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_customer_first_name_customer_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='comments',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='ratings_dict',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='total_reviews',
            field=models.IntegerField(default=0),
        ),
    ]
