# Generated by Django 5.2.7 on 2025-10-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_serviceprovider_comments_serviceprovider_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='comments',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
