# Generated by Django 5.2.7 on 2025-11-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_alter_serviceprovider_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='comments',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
