# Generated by Django 5.2.7 on 2025-11-12 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0002_alter_travelblog_options_forum_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='route',
        ),
    ]
