# Generated by Django 5.2.7 on 2025-10-22 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='service_id',
        ),
        migrations.AddField(
            model_name='booking',
            name='content_type',
            field=models.ForeignKey(blank=True, help_text='The model of the service being booked (e.g., BusService, TrainService).', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='booking',
            name='object_id',
            field=models.UUIDField(blank=True, help_text='The UUID of the specific service instance.', null=True),
        ),
    ]
