# Generated by Django 5.2.7 on 2025-10-22 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_booking_mode_remove_booking_service_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='no_cancellation_free_markup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='no_reschedule_free_markup',
            field=models.BooleanField(default=False),
        ),
    ]
