# Generated by Django 5.2.7 on 2025-10-24 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingpassenger',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='bookings.booking'),
        ),
    ]
