# Generated by Django 5.2.7 on 2025-10-28 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_bookingpassenger_booking'),
        ('services', '0012_busservice_bus_number_busservice_bus_travels_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='destination_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_destination_station', to='services.station'),
        ),
        migrations.AddField(
            model_name='booking',
            name='source_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_source_station', to='services.station'),
        ),
    ]
