# Generated by Django 5.2.7 on 2025-10-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_destination_id_booking_source_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='class_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
